highlighter: 'rouge'
markdown: kramdown
kramdown:
  footnote_backlink: "⤻"
url: http://xpmethod.plaintext.in/
future: true
permalink: none

# Required if you want to move pages into a a separate directory
# not working at the moment for some reason
include: ['_pages']
# relative_permalinks: false

# Since Travis installs gems to /vendor, we have to remove
# this to keep Travis from checking everything in /vendor.
exclude: ['vendor', 'doc', 'README.md']

# enable redirects
plugins:
  - jekyll-redirect-from

# for use with --safe mode to mimic github pages
whitelist: 
  - jekyll-redirect-from

collections_dir: collections
collections:
  events:
    output: true
  lit-mod-viz:
    output: true
  embodied-space-lab:
    output: true
  knowledge-design-studio:
    output: true
  epistemic-action:
    output: true
  clusters:
    output: true

# specifies default layouts for all items in collection subfolders
defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "clusters"
    values:
      layout: "cluster"
  - scope:
      path: ""
      type: "lit-mod-viz"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "knowledge-design-studio"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "embodied-space-lab"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "epistemic-action"
    values:
      layout: "project"
