highlighter: 'rouge'
markdown: kramdown
kramdown:
  footnote_backlink: '&#x21A9;&#xFE0E;'
url: http://xpmethod.plaintext.in/
future: true
permalink: none

# Required if you want to move pages into a a separate directory
# not working at the moment for some reason
include: ['_pages']
# relative_permalinks: false

# Since Travis installs gems to /vendor, we have to remove
# this to keep Travis from checking everything in /vendor.
exclude: ['vendor', 'doc', 'README.md']

# enable redirects
plugins: []
    #    - jekyll-redirect-from

collections_dir: collections
collections:
  events:
    description: "test 1"
  lit-mod-viz:
    description: "test 2"
  embodied-space-lab:
    description: "test 3"
  knowledge-design-studio:
    description: "test 4"
  epistemic-action:
    description: "test 5"

